/**
 * Generates per-method test files for every wrapper.
 *
 * Reads `src/generated/prompts.json` (produced by `generate-wrappers.ts`)
 * and emits one test file per group under `tests/generated/<group>.test.ts`.
 * Each method gets a parameterised set of scenarios that exercises the
 * routing layer (LLM dispatch, native fallback, empty-prompt-as-native)
 * plus the error paths every working dev hits at least once
 * (network outage, proxy 5xx, malformed LLM response, missing key).
 *
 * The grid is built with `it.each` so 654 methods x 5 scenarios still
 * runs in well under a minute. Mocked dependencies (fetch / OpenAI) are
 * reset per case to keep the tests isolated.
 */
import { readFileSync, mkdirSync, writeFileSync, existsSync, rmSync, readdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const PKG_ROOT = resolve(__dirname, '..');
const PROMPTS_JSON = resolve(PKG_ROOT, 'src/generated/prompts.json');
const TESTS_OUT_DIR = resolve(PKG_ROOT, 'tests/generated');

interface Entry {
  group: string;
  methodName: string;
  functionId: string;
  kind: 'instance' | 'static' | 'global';
  receiverKey: string;
  paramOrder: string[];
  variadicKey: string;
  curated: { prompt: string; comment: string; example: string };
}

const ALL = JSON.parse(readFileSync(PROMPTS_JSON, 'utf8')) as Record<string, Entry>;

function groupBy(): Record<string, Entry[]> {
  const out: Record<string, Entry[]> = {};
  for (const entry of Object.values(ALL)) {
    (out[entry.group] = out[entry.group] || []).push(entry);
  }
  for (const list of Object.values(out)) list.sort((a, b) => a.methodName.localeCompare(b.methodName));
  return out;
}

/**
 * Build the per-method input expression for the LLM-routing scenario.
 * The expression is rendered into the test file as JavaScript: it
 * always sets `prompt: 'test'` and stubs every named parameter with
 * `undefined`. The mocked fetch only inspects `functionId`, so input
 * faithfulness beyond that does not matter.
 *
 * Returns the inner content of the input object (without surrounding `{}`)
 * so the test author can inject extra context.
 */
function buildInputExpr(entry: Entry, includePrompt: boolean): string {
  const fields: string[] = [];
  if (entry.kind === 'instance' && entry.receiverKey) {
    fields.push(`${entry.receiverKey}: undefined`);
  }
  for (const name of entry.paramOrder) {
    if (name === entry.variadicKey) continue;
    fields.push(`${name}: undefined`);
  }
  if (entry.variadicKey) fields.push(`${entry.variadicKey}: []`);
  if (includePrompt) fields.push(`prompt: 'test'`);
  return `{ ${fields.join(', ')} }`;
}

function renderGroupTestFile(group: string, entries: Entry[]): string {
  const dottedAccess = (e: Entry) =>
    e.group === 'globals' ? `neuro.${e.methodName}` : `neuro.${e.group}.${e.methodName}`;

  const cases = entries
    .map(
      (e) => `  {
    name: '${e.methodName}',
    functionId: '${e.functionId}',
    routedInput: ${buildInputExpr(e, true)},
    nativeInput: ${buildInputExpr(e, false)},
    invoke: (input) => (${dottedAccess(e)} as (i: Record<string, unknown>) => Promise<unknown>)(input),
  }`,
    )
    .join(',\n');

  return `// Auto-generated by scripts/generate-tests.ts. Do not edit.
// Per-method routing & error-path tests for the \`${group}\` group.
/* eslint-disable import/no-relative-packages */
import { afterEach, describe, expect, test, vi } from 'vitest';
import { configureClient, neuro, resetClient } from '../../dist/index.js';

interface MethodCase {
  name: string;
  functionId: string;
  routedInput: Record<string, unknown>;
  nativeInput: Record<string, unknown>;
  invoke: (input: Record<string, unknown>) => Promise<unknown>;
}

const cases: MethodCase[] = [
${cases}
];

afterEach(() => {
  resetClient();
  vi.unstubAllGlobals();
  vi.restoreAllMocks();
});

describe('${group} routing', () => {
  test.each(cases)('$name routes to LLM when prompt is set', async ({ functionId, routedInput, invoke }) => {
    const fetchMock = vi.fn(
      async () =>
        new Response(JSON.stringify({ result: null }), {
          status: 200,
          headers: { 'content-type': 'application/json' },
        }),
    );
    vi.stubGlobal('fetch', fetchMock);
    configureClient({ proxyUrl: 'https://example.test/neuro' });
    await invoke(routedInput);
    expect(fetchMock).toHaveBeenCalledOnce();
    const sent = JSON.parse(String(fetchMock.mock.calls[0][1]?.body));
    expect(sent.functionId).toBe(functionId);
    expect(sent.prompt).toBe('test');
  });

  test.each(cases)('$name does not call the LLM when prompt is omitted', async ({ nativeInput, invoke }) => {
    const fetchMock = vi.fn();
    vi.stubGlobal('fetch', fetchMock);
    configureClient({ proxyUrl: 'https://example.test/neuro' });
    // We do not assert the native return value (many methods need real
    // arguments to run); we only assert that fetch is never invoked.
    await invoke(nativeInput).catch(() => {
      /* native may throw with stub args; the routing decision is what
       * we are testing here. */
    });
    expect(fetchMock).not.toHaveBeenCalled();
  });

  test.each(cases)('$name treats prompt: "" as absent (no LLM call)', async ({ nativeInput, invoke }) => {
    const fetchMock = vi.fn();
    vi.stubGlobal('fetch', fetchMock);
    configureClient({ proxyUrl: 'https://example.test/neuro' });
    await invoke({ ...nativeInput, prompt: '' }).catch(() => {});
    expect(fetchMock).not.toHaveBeenCalled();
  });

  test.each(cases)('$name surfaces network outage as NeuroClientError', async ({ functionId, routedInput, invoke }) => {
    vi.stubGlobal('fetch', async () => {
      throw new Error('network down');
    });
    configureClient({ proxyUrl: 'https://example.test/neuro' });
    await expect(invoke(routedInput)).rejects.toThrow(/Proxy fetch failed/);
    // The thrown error includes the functionId for postmortems.
    await expect(invoke(routedInput)).rejects.toThrow(new RegExp(functionId.replace(/[.\\\\]/g, '\\\\$&')));
  });

  test.each(cases)('$name surfaces a 500 from the proxy', async ({ routedInput, invoke }) => {
    vi.stubGlobal(
      'fetch',
      async () => new Response('boom', { status: 500, statusText: 'Server Error' }),
    );
    configureClient({ proxyUrl: 'https://example.test/neuro' });
    await expect(invoke(routedInput)).rejects.toThrow(/Proxy.*responded 500/);
  });
});
`;
}

function run(): void {
  if (existsSync(TESTS_OUT_DIR)) {
    for (const entry of readdirSync(TESTS_OUT_DIR)) {
      rmSync(resolve(TESTS_OUT_DIR, entry), { recursive: true, force: true });
    }
  }
  mkdirSync(TESTS_OUT_DIR, { recursive: true });
  const grouped = groupBy();
  let total = 0;
  for (const [group, entries] of Object.entries(grouped).sort(([a], [b]) => a.localeCompare(b))) {
    const file = resolve(TESTS_OUT_DIR, `${group}.test.ts`);
    writeFileSync(file, renderGroupTestFile(group, entries));
    total += entries.length;
  }
  console.log(
    `[generate-tests] wrote ${Object.keys(grouped).length} group files covering ${total} methods -> tests/generated/`,
  );
}

run();
